# Generated by Django 2.2.15 on 2020-08-03 10:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('03719950-572a-4998-8d4a-dd3a5e993ee3'), verbose_name='用户JWT秘钥'),
        ),
    ]
