# Generated by Django 2.2.15 on 2020-08-07 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccounts_user_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('bd0d402e-6ff8-4f4e-9a70-679722f0b937'), verbose_name='用户JWT秘钥'),
        ),
    ]
