# Generated by Django 3.1 on 2020-08-10 13:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200807_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('71a23a24-432d-451b-b56d-4cad2832af11'), verbose_name='用户JWT秘钥'),
        ),
    ]
