# Generated by Django 3.1 on 2020-08-25 13:35

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200810_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('b64623c4-7c36-4bb0-91b1-c38d280db3e0'), verbose_name='用户JWT秘钥'),
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('role_name', models.CharField(max_length=30, verbose_name='角色名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
                'db_table': 'yasql_user_roles',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('permission_name', models.CharField(max_length=30, verbose_name='权限名')),
                ('permission_desc', models.CharField(default='', max_length=30, verbose_name='权限描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.ManyToManyField(to='users.UserRoles')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
                'db_table': 'yasql_role_permissions',
                'default_permissions': (),
            },
        ),
    ]
