# Generated by Django 3.1 on 2020-09-02 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200825_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='department',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='user_secret',
            field=models.UUIDField(default=uuid.UUID('fe266d03-e0c4-4217-a7eb-3f5fdb234ef3'), verbose_name='用户JWT秘钥'),
        ),
    ]
