# Generated by Django 3.1 on 2020-08-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbEnvironment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'DB环境',
                'verbose_name_plural': 'DB环境',
                'db_table': 'yasql_db_environment',
                'default_permissions': (),
            },
        ),
    ]
