# Generated by Django 3.1 on 2020-08-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0003_dbconfig_dborders_dbordersexecutetasks_dbschemas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbconfig',
            name='is_enabled',
            field=models.CharField(choices=[(0, '启用'), (1, '禁用')], default=0, max_length=1, verbose_name='是否启用'),
        ),
    ]
