# Generated by Django 3.1 on 2020-08-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0004_auto_20200812_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbconfig',
            name='is_enabled',
            field=models.SmallIntegerField(choices=[(0, '启用'), (1, '禁用')], default=0, verbose_name='是否启用'),
        ),
    ]
