# Generated by Django 3.1 on 2020-08-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0005_auto_20200812_1307'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dbordersexecutetasks',
            table='yasql_sqlorders_execute_tasks',
        ),
    ]
