# Generated by Django 3.1 on 2020-09-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0007_auto_20200901_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dborders',
            name='email_cc',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='抄送人'),
        ),
    ]
