# Generated by Django 3.1 on 2020-09-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlorders', '0008_auto_20200901_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='dborders',
            name='department',
            field=models.CharField(blank=True, max_length=128, verbose_name='申请人所在的部门'),
        ),
    ]
